[package]
name = "ripioc"
version = "0.1.0"
authors = ["Oliver Daff <oliverdaff@users.noreply.github.com>"]
edition = "2018"

[features]
serde_support = ["serde"]

[dependencies]
regex = "1"
lazy_static = "1.4.0"
serde = { version = "1",  features = ["derive"], optional = true }
